### PR TITLE
Add auto complete for header key input.  Updates #5

### PR DESCRIPTION
**Pull request by Le-Roi777**
- Updates #5

- Added a request headers array list for the Autocomplete component.
- Added Autocomplete component and updated the onChange events/functions.

auto1
auto2

### CODE REVIEW

**Review by kursataktas — COMMENTED** [review]
Great work @Le-Roi777 💯 

The only thing we have to fix is the alignment of the delete button

image

**Comment by Le-Roi777** [comment]
aaah yes...! fixed it 👍🏼

**Review by kursataktas — APPROVED** [review]
Great work, thank you for your effort 🥇 🎊

**Comment by Le-Roi777** [comment]
> Great work, thank you for your effort 🥇 🎊

👍

**Comment by AlbaRoza** [comment]
Hi @Le-Roi777 this is Alba from Docker. Can you send me an email to alba.roza@docker.com? I have exciting news on Hacktoberfest for you! Thanks!

**Pull request merged**
